export const USERNAME = {
  NOUN: [
    'cool',
    'happy',
    'fuzzy',
    'brave',
    'smart',
    'funny',
    'crazy',
    'silly',
    'witty',
    'clever',
    'kind',
    'gentle',
    'calm',
    'quiet',
  ],
  ADJECTIVE: [
    'cat',
    'dog',
    'tiger',
    'lion',
    'panda',
    'bear',
    'wolf',
    'fox',
    'rabbit',
    'mouse',
    'squirrel',
    'hamster',
    'guinea pig',
    'hedgehog',
    'ferret',
    'chinchilla',
    'gerbil',
    'rabbit',
    'mouse',
    'squirrel',
    'hamster',
    'guinea pig',
    'hedgehog',
    'ferret',
    'chinchilla',
    'gerbil',
    'rabbit',
    'mouse',
    'squirrel',
    'hamster',
    'guinea pig',
    'hedgehog',
    'ferret',
    'chinchilla',
    'gerbil',
    'rabbit',
    'mouse',
    'squirrel',
    'hamster',
    'guinea pig',
    'hedgehog',
    'ferret',
    'chinchilla',
    'gerbil',
    'rabbit',
    'mouse',
    'squirrel',
    'hamster',
    'guinea pig',
    'hedgehog',
    'ferret',
    'chinchilla',
    'gerbil',
    'rabbit',
    'mouse',
    'squirrel',
    'hamster',
    'guinea pig',
    'hedgehog',
    'ferret',
    'chinchilla',
    'gerbil',
    'rabbit',
    'mouse',
    'squirrel',
    'hamster',
    'guinea pig',
    'hedgehog',
    'ferret',
    'chinchilla',
    'gerbil',
    'rabbit',
    'mouse',
    'squirrel',
    'hamster',
    'guinea pig',
    'hedgehog',
    'ferret',
    'chinchilla',
    'gerbil',
    'rabbit',
    'mouse',
    'squirrel',
    'hamster',
    'guinea pig',
    'hedgehog',
    'ferret',
    'chinchilla',
    'gerbil',
    'rabbit',
    'mouse',
    'squirrel',
    'hamster',
    'guinea pig',
    'hedgehog',
    'ferret',
    'chinchilla',
    'gerbil',
    'rabbit',
    'mouse',
    'squirrel',
    'hamster',
    'guinea pig',
    'hedgehog',
    'ferret',
    'chinchilla',
    'gerbil',
    'rabbit',
    'mouse',
    'squirrel',
    'hamster',
    'guinea pig',
    'hedgehog',
    'ferret',
    'chinchilla',
    'gerbil',
    'rabbit',
    'mouse',
    'squirrel',
  ],
};
